### ISSUE TITLE
Spark Button

### ISSUE THREAD

**Issue by kalisnetwork** [juxtopposed/stacksorted#13]
The Spark Button has a Codepen link that directly redirects to the Codepen site. However, it should redirect to the original website, and users should be able to check the code there instead, as the Codepen link is already available.
![codeissue](https://github.com/juxtopposed/stacksorted/assets/106701723/d147d94a-d40a-4107-a905-5abb628982fb)

**Comment by amanbobal** [comment]
I think it's just a standalone Pen from Codepen and not from a particular website.

**Comment by amanbobal** [comment]
@juxtopposed is it okay to submit these pens to StackSorted? Cuz I have a ton of cool pens to show.🙂

Regards❤️

**Comment by juxtopposed** [comment]
Hey there. Yeah it is okay to submit pens. But if a pen is based on a design/live site, then you can submit both and the pen would be linked to "Check Code"
I think I'll have to disable the CodePen link for designs that originate on CodePen.

**Comment by kalisnetwork** [comment]
May be like url ?: String or code?: String either one of them should be optional or either one should display.
