### ISSUE TITLE
More categories?

### ISSUE THREAD

**Issue by Prestopy** [juxtopposed/stacksorted#2]
# More element types
The current [Stack Sorted](https://stacksorted.com/) website has 4 categories: **button, links, grids, custom cursor**. However, I feel like there are definitely more categories that could be added as nowadays, there are lots more elements that may look good on websites but don't fit in any of those categories. For example, menus, color & styling, typography, interactivity, visuals, animations, etc.

_I probably missed lots of things but I feel like there should definitely be more categories._

**Comment by kalisnetwork** [comment]
categories: {
    "buttons": [
      {
        name: "Flowchef",
        url: "https://www.flowchef.co/",
        image: "/images/buttons-1.webp",
        code: "https://codepen.io/ThunderFound/pen/QWJBQwo",
      },],
    "links": [
      {
        name: "Oaks Lane",
        url: "https://oakslane.ch/en",
        image: "/images/links-1.webp",
        gif: "/images/links-1g.webp",
      },],
"New Category":[
name:"",
url:"",
image:"",
],

**Comment by juxtopposed** [comment]
Hey @Prestopy @kalisnetwork thanks guys. Now that we have more categories I think we can close this. But feel free to add whatever category you like.
