### ISSUE TITLE
Enhancement: footer design changes

### ISSUE THREAD

**Issue by wasimapinjari** [juxtopposed/stacksorted#29]
What do you think? 🥰

Before:

![Screenshot (268)](https://github.com/juxtopposed/stacksorted/assets/95426296/547ef1f7-c72d-4a46-ab14-67dd5fd24a45)

After:

![Screenshot (269)](https://github.com/juxtopposed/stacksorted/assets/95426296/0ea905cb-37be-4bc7-881f-329d73145d05)

**Comment by juxtopposed** [comment]
Hi, sorry for the late reply. I'm afraid this is not a necessary update. Please check [Code of Conduct](https://github.com/juxtopposed/stacksorted/blob/main/CONTRIBUTIONS.md) for reference.
