### ISSUE TITLE
Fix modal overflow issue in Stack Sorted

### ISSUE THREAD

**Issue by mh-jsx** [juxtopposed/stacksorted#34]
### Problem
The modal in Stack Sorted currently has a fixed height, which causes images to overflow when their dimensions exceed the modal's dimensions. This results in a poor user experience and hides action buttons.

### Proposed Solution
To address this issue, we should set the CSS property of images within the modal to "overflow: auto" so that they do not overflow from their parent container.

### Steps to Reproduce
1. Open a website. [stacksorted](https://stacksorted.com)
2. Click on any of the card with large image e.g:  [Border effects Vercel](https://stacksorted.com/border-effects/vercel)
3. Observe the image overflowing from the modal.

### Expected Behavior
Images within the modal should not overflow from the modal's image area.

### Additional Information
- Stack Sorted version: 1.0.0
- Browser: Chrome

**Comment by juxtopposed** [comment]
Closing as completed in #35
