### ISSUE TITLE
Regarding Submissions

### ISSUE THREAD

**Issue by Stranger1586** [juxtopposed/stacksorted#38]
Do you still accept submissions?
I ask this because I made one for the resend cube scene [https://codepen.io/stranger1586/full/RwvjmdW](url) that I feel (perhaps wrongfully) looks close enough to the original to be accepted, I plan on making even more submissions, but I wont if they are not even going to be reviewed.
I know this isn't really the place to discuss this, but there exists no other forum to discuss such matters.

**Comment by juxtopposed** [comment]
Hi there! Yeah sure! Feel free to submit a PR. Or let me know if I should just add the link. (Looks great btw!)

**Comment by Stranger1586** [comment]
I will submit a PR, in a bit, glad you liked it.
