### ISSUE TITLE
Add Navbar section

### ISSUE THREAD

**Issue by marcusleonas** [juxtopposed/stacksorted#50]
Would be useful to a lot of people, maybe a responsive navbar section as well.

**Comment by Dedphish** [comment]
Agreed, was looking for this today actually

**Comment by juxtopposed** [comment]
Hey there, something like the [Headers sections](https://stacksorted.com/headers)?

**Comment by flvffywvffy** [comment]
> Hey there, something like the [Headers sections](https://stacksorted.com/headers)?

Ahh, I assumed that headers was for heros, not navbars. Thanks!
