### ISSUE TITLE
Need "Header" Category

### ISSUE THREAD

**Issue by ThunderFound** [juxtopposed/stacksorted#9]
Want some inspiration :)

**Comment by juxtopposed** [comment]
Searching...

**Comment by cohenerickson** [comment]
I just was thinking to myself that I should look here for some header inspiration, I'll definitely submit a site if I stumble across some cool designs.

**Comment by kalisnetwork** [comment]
May be Stack sorted. has new category called "Headers" or may be "Footers". They are also elements right?.....

**Comment by kalisnetwork** [comment]
![image](https://github.com/juxtopposed/stacksorted/assets/106701723/32dac545-ef3a-4e01-8ad7-99d151d62611)

Surprisingly my codepen got into trending!!

**Comment by kalisnetwork** [comment]
![image](https://github.com/juxtopposed/stacksorted/assets/106701723/78c41d40-375a-4f4b-a452-a23451496271)
Surprisingly my CodePen got into trending!!

**Comment by juxtopposed** [comment]
Just saw that @kalisnetwork very nice :)

**Comment by juxtopposed** [comment]
I've added this category recently. Could definitely use more designs, though. Closing this as resolved.
